/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_hadoop_io_erasurecode_rawcoder_NativeXORRawDecoder */

#ifndef _Included_org_apache_hadoop_io_erasurecode_rawcoder_NativeXORRawDecoder
#define _Included_org_apache_hadoop_io_erasurecode_rawcoder_NativeXORRawDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_hadoop_io_erasurecode_rawcoder_NativeXORRawDecoder
 * Method:    loadLib
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_io_erasurecode_rawcoder_NativeXORRawDecoder_loadLib
  (JNIEnv *, jclass);

/*
 * Class:     org_apache_hadoop_io_erasurecode_rawcoder_NativeXORRawDecoder
 * Method:    init
 * Signature: (II[I)I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_io_erasurecode_rawcoder_NativeXORRawDecoder_init
  (JNIEnv *, jclass, jint, jint, jintArray);

/*
 * Class:     org_apache_hadoop_io_erasurecode_rawcoder_NativeXORRawDecoder
 * Method:    decode
 * Signature: ([Ljava/nio/ByteBuffer;[II)I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_io_erasurecode_rawcoder_NativeXORRawDecoder_decode
  (JNIEnv *, jclass, jobjectArray, jintArray, jint);

/*
 * Class:     org_apache_hadoop_io_erasurecode_rawcoder_NativeXORRawDecoder
 * Method:    destroy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_io_erasurecode_rawcoder_NativeXORRawDecoder_destroy
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
