/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_hadoop_io_erasurecode_rawcoder_util_IsalUtil */

#ifndef _Included_org_apache_hadoop_io_erasurecode_rawcoder_util_IsalUtil
#define _Included_org_apache_hadoop_io_erasurecode_rawcoder_util_IsalUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_hadoop_io_erasurecode_rawcoder_util_IsalUtil
 * Method:    loadLibrary
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_io_erasurecode_rawcoder_util_IsalUtil_loadLibrary
  (JNIEnv *, jclass);

/*
 * Class:     org_apache_hadoop_io_erasurecode_rawcoder_util_IsalUtil
 * Method:    getLibraryName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_apache_hadoop_io_erasurecode_rawcoder_util_IsalUtil_getLibraryName
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
