/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_hadoop_io_erasurecode_rawcoder_ISARSRawEncoder */

#ifndef _Included_org_apache_hadoop_io_erasurecode_rawcoder_ISARSRawEncoder
#define _Included_org_apache_hadoop_io_erasurecode_rawcoder_ISARSRawEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_hadoop_io_erasurecode_rawcoder_ISARSRawEncoder
 * Method:    loadLib
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_io_erasurecode_rawcoder_ISARSRawEncoder_loadLib
  (JNIEnv *, jclass);

/*
 * Class:     org_apache_hadoop_io_erasurecode_rawcoder_ISARSRawEncoder
 * Method:    init
 * Signature: (II[I)I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_io_erasurecode_rawcoder_ISARSRawEncoder_init
  (JNIEnv *, jclass, jint, jint, jintArray);

/*
 * Class:     org_apache_hadoop_io_erasurecode_rawcoder_ISARSRawEncoder
 * Method:    encode
 * Signature: ([Ljava/nio/ByteBuffer;[Ljava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_io_erasurecode_rawcoder_ISARSRawEncoder_encode
  (JNIEnv *, jclass, jobjectArray, jobjectArray, jint);

/*
 * Class:     org_apache_hadoop_io_erasurecode_rawcoder_ISARSRawEncoder
 * Method:    destroy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_io_erasurecode_rawcoder_ISARSRawEncoder_destroy
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
