/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_hadoop_hdfs_ec_rawcoder_IsaRSRawEncoder */

#ifndef _Included_org_apache_hadoop_hdfs_ec_rawcoder_IsaRSRawEncoder
#define _Included_org_apache_hadoop_hdfs_ec_rawcoder_IsaRSRawEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_hadoop_hdfs_ec_rawcoder_IsaRSRawEncoder
 * Method:    init
 * Signature: (II[I)I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_hdfs_ec_rawcoder_IsaRSRawEncoder_init
  (JNIEnv *, jclass, jint, jint, jintArray);

/*
 * Class:     org_apache_hadoop_hdfs_ec_rawcoder_IsaRSRawEncoder
 * Method:    encode
 * Signature: ([Ljava/nio/ByteBuffer;[Ljava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_hdfs_ec_rawcoder_IsaRSRawEncoder_encode
  (JNIEnv *, jclass, jobjectArray, jobjectArray, jint);

/*
 * Class:     org_apache_hadoop_hdfs_ec_rawcoder_IsaRSRawEncoder
 * Method:    destroy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_hdfs_ec_rawcoder_IsaRSRawEncoder_destroy
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
