/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_hadoop_hdfs_ec_rawcoder_IsaRSRawEncoder */

#ifndef _Included_org_apache_hadoop_hdfs_ec_rawcoder_IsaRSRawEncoder
#define _Included_org_apache_hadoop_hdfs_ec_rawcoder_IsaRSRawEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_hadoop_hdfs_ec_rawcoder_IsaRSRawEncoder
 * Method:    jni_init
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_hdfs_ec_rawcoder_IsaRSRawEncoder_jni_1init
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_apache_hadoop_hdfs_ec_rawcoder_IsaRSRawEncoder
 * Method:    jni_encode
 * Signature: ([Ljava/nio/ByteBuffer;[Ljava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_hdfs_ec_rawcoder_IsaRSRawEncoder_jni_1encode
  (JNIEnv *, jclass, jobjectArray, jobjectArray, jint);

/*
 * Class:     org_apache_hadoop_hdfs_ec_rawcoder_IsaRSRawEncoder
 * Method:    jni_destroy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_hdfs_ec_rawcoder_IsaRSRawEncoder_jni_1destroy
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
