/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_hadoop_raid_ReedSolomonDecoder2 */

#ifndef _Included_org_apache_hadoop_raid_ReedSolomonDecoder2
#define _Included_org_apache_hadoop_raid_ReedSolomonDecoder2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_hadoop_raid_ReedSolomonDecoder2
 * Method:    isaDeInit
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_raid_ReedSolomonDecoder2_isaDeInit
  (JNIEnv *, jclass, jint, jint, jintArray);

/*
 * Class:     org_apache_hadoop_raid_ReedSolomonDecoder2
 * Method:    isaDecode
 * Signature: ([Ljava/nio/ByteBuffer;[II)I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_raid_ReedSolomonDecoder2_isaDecode
  (JNIEnv *, jclass, jobjectArray, jintArray, jint);

/*
 * Class:     org_apache_hadoop_raid_ReedSolomonDecoder2
 * Method:    isaDeEnd
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_raid_ReedSolomonDecoder2_isaDeEnd
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
