/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_hadoop_hdfs_ec_rawcoder_IsaRSRawDecoder */

#ifndef _Included_org_apache_hadoop_hdfs_ec_rawcoder_IsaRSRawDecoder
#define _Included_org_apache_hadoop_hdfs_ec_rawcoder_IsaRSRawDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_hadoop_hdfs_ec_rawcoder_IsaRSRawDecoder
 * Method:    jni_init
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_hdfs_ec_rawcoder_IsaRSRawDecoder_jni_1init
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_apache_hadoop_hdfs_ec_rawcoder_IsaRSRawDecoder
 * Method:    jni_decode
 * Signature: ([Ljava/nio/ByteBuffer;[II)I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_hdfs_ec_rawcoder_IsaRSRawDecoder_jni_1decode
  (JNIEnv *, jclass, jobjectArray, jintArray, jint);

/*
 * Class:     org_apache_hadoop_hdfs_ec_rawcoder_IsaRSRawDecoder
 * Method:    jni_destroy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_hdfs_ec_rawcoder_IsaRSRawDecoder_jni_1destroy
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
