/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_hadoop_raid_ReedSolomonEncoder2 */

#ifndef _Included_org_apache_hadoop_raid_ReedSolomonEncoder2
#define _Included_org_apache_hadoop_raid_ReedSolomonEncoder2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_hadoop_raid_ReedSolomonEncoder2
 * Method:    isaEnInit
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_raid_ReedSolomonEncoder2_isaEnInit
  (JNIEnv *, jclass, jint, jint, jintArray);

/*
 * Class:     org_apache_hadoop_raid_ReedSolomonEncoder2
 * Method:    isaEncode
 * Signature: ([Ljava/nio/ByteBuffer;[Ljava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_raid_ReedSolomonEncoder2_isaEncode
  (JNIEnv *, jclass, jobjectArray, jobjectArray, jint);

/*
 * Class:     org_apache_hadoop_raid_ReedSolomonEncoder2
 * Method:    isaEnEnd
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_raid_ReedSolomonEncoder2_isaEnEnd
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
