#!/bin/bash
# this file execute given command on each slaves
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
for slave in `$SCRIPT_DIR/get-slaves`
do
  echo "###########SERVER:$slave############"
  ssh $slave "$1"
done
